services:
  postgres:
    container_name: postgres-spring-boot
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    env_file:
      - .env
    networks:
      - db
    restart: unless-stopped
  elasticsearch:
    image: elasticsearch:8.19.4
    container_name: codesearch-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data


networks:
  db:
    driver: bridge

volumes:
  db:
  esdata:
